// Created by iWeb 2.0.4 local-build-20110111

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,76),url:'Research_Papers_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'Research_Papers_files/stroke_1.png'},{rect:new IWRect(5,-5,204,10),url:'Research_Papers_files/stroke_2.png'},{rect:new IWRect(209,-5,10,10),url:'Research_Papers_files/stroke_3.png'},{rect:new IWRect(209,5,10,76),url:'Research_Papers_files/stroke_4.png'},{rect:new IWRect(209,81,10,11),url:'Research_Papers_files/stroke_5.png'},{rect:new IWRect(5,81,204,11),url:'Research_Papers_files/stroke_6.png'},{rect:new IWRect(-5,81,10,11),url:'Research_Papers_files/stroke_7.png'}],new IWSize(214,86)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,37),url:'Research_Papers_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Research_Papers_files/stroke_9.png'},{rect:new IWRect(1,-1,391,2),url:'Research_Papers_files/stroke_10.png'},{rect:new IWRect(392,-1,2,2),url:'Research_Papers_files/stroke_11.png'},{rect:new IWRect(392,1,2,37),url:'Research_Papers_files/stroke_12.png'},{rect:new IWRect(392,38,2,2),url:'Research_Papers_files/stroke_13.png'},{rect:new IWRect(1,38,391,2),url:'Research_Papers_files/stroke_14.png'},{rect:new IWRect(-1,38,2,2),url:'Research_Papers_files/stroke_15.png'}],new IWSize(393,39))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Research_Papers_files/Research_PapersMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixAllIEPNGs('Media/transparent.gif');IMpreload('Research_Papers_files','shapeimage_2','0');IMpreload('Research_Papers_files','shapeimage_2','1');IMpreload('Research_Papers_files','shapeimage_2','2');IMpreload('Research_Papers_files','shapeimage_2','3');IMpreload('Research_Papers_files','shapeimage_2','4');applyEffects()}
function onPageUnload()
{Widget.onunload();}
